<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise Method</title>
</head>
<body>
    <h1 style="border : 1px solid black;">Promise Object in Javascript</h1>
    
    <script>
        // const promiseObj = new Promise( (resolve, reject) =>{
        //   let req = true;
        //   if(req == true){
        //          resolve("Promise Accepted");
        //         // resolve([1,2,3,4,5]);
        //   } else {
        //          reject("Promise Rejected");
        //   }
        // })

        // promiseObj.then(
        //     (value) => { console.log(value); },
        //     (error) => { console.log(error); }
        // )

        // const promiseObj = new Promise( (resolve, reject) =>{
        //   let req = false;
        //   if(req == true){
        //          resolve("Promise Accepted");
        //         // resolve([1,2,3,4,5]);
        //   } else {
        //          reject("Promise Rejected");
        //   }
        // }).then(
        //     (value) => { console.log(value); }
        // ).catch(
        //     (error) => { console.log(error); }
        // )

        //============Promise chaining in javascript----------
        // const promiseObj = new Promise( (resolve, reject) =>{
        //     let num = 10;
        //     resolve(num);
        // }).then(
        //     (value) => { console.log(value); 
        //         return value+10; 
        //     }
        // ).then(
        //     (value) => { console.log(value); }
        // )
 //===============Promise chaining and catch , finally method
        // const promiseObj = new Promise( (resolve, reject) =>{
        //     let req = false;
        //     if(req == true){
        //         resolve("Promise Accepted");
        //     } else {
        //         reject("Promise Rejected");
        //     }
        // }).then(
        //     (value) => { console.log(value); 
        //         return value+10; 
        //     }
        // ).then(
        //     (value) => { console.log(value); }
        // ).catch(
        //     (error) => { console.log(error); }
        // ).finally( () => {
        //     console.log("All tasks are done"); 
        // }
        // )


        //======Aynsc and Await in javascript------------------------------
        console.log("start");
        function getName(name){
           return new Promise( (resolve , reject) => {
            setTimeout(() => {
                console.log("Inside Name SetTimeout ");
                resolve(name);
            }, 1000);
           })
        }

        function getHobby(hobby){
          return new Promise( (resolve, reject) => {
            console.log("Inside Hobbies setTimeout");
            setTimeout( () => {
                resolve(['Badminton','Dancing', 'Playing Chess']);
            }, 1000);
          })
        }
        
        //get Data using promise consuming code method
        // getName('Daksh')
        // .then( nm => getHobby(nm))
        // .then( hobby => console.log(hobby))

        //get data using async and await functon
        // async function showHobby(){
        //     const nm = await getName('Daksh');
        //     const hobby = await getHobby(nm);
        //     console.log(hobby);
        // }

        //get data using async and await functon if any error happens there then we simple use exception handling for solving error

        async function showHobby(){
            try{
             const nm = await getName('Daksh');
            const hobby = await getHobby(nm);
            console.log(hobby);
            }
            catch{
                console.log("error happens");
            } 
        }


        // showHobby();
        console.log("end");
    </script>
</body>
</html>